# 使用官方的Java运行环境作为基础镜像
FROM openjdk:17-jre-slim

# 指定容器内的工作目录
WORKDIR /app

# 将编译完成后的jar文件复制到容器中
COPY /code/webfluxdemo/webfluxdemo-0.0.1-plain.jar /app/webfluxdemo-0.0.1-plain.jar

# 设置容器需要开放的端口
EXPOSE 8080

# 配置当容器启动时运行的命令
ENTRYPOINT ["java", "-jar", "webfluxdemo-0.0.1-plain.jar"]
